### ISSUE TITLE
eq3_v2 component doesn't want to work

### ISSUE THREAD

**Issue by Wojcioo** [ayufan/esphome-components#21]
Hello
I'm trying to implement eq3_v2 component, but it doesn't want to compile in esphome because of the error "Platform not found: 'climate.eq3_v2'.
Here is part of my config:

```
esphome:
  name: esp32-eq3-gateway
  platform: ESP32
  board: esp32dev

logger:

api:

ota:

wifi:
  ssid: 'Home automation'
  password: 'secretpassword'

  ap:
    ssid: "Esp32-Eq3-Gateway"
    password: "password"

captive_portal:

web_server:
  port: 80
  
external_components:
  - source: github://ayufan/esphome-components

esp32_ble_tracker:

sensor:
  - platform: ble_rssi
    mac_address: 03:14:54:0E:0A:5B
    name: "EQ3 valve"

time:
  - platform: sntp
    id: sntp_time
    
climate:
  - platform: eq3_v2
    id: office_eq3
    name: Bathroom EQ3
    mac_address: 03:14:54:0E:0A:5B
    update_interval: 30min
    valve:
      name: Bathroom EQ3 Valve State
      expire_after: 61min
```

I'm using ESPHome 2021.9.3.
Kind regards

**Comment by ayufan** [comment]
Thanks. I thought that I updated this. Will try again :)

**Comment by jperquin** [comment]
Are you sure you want to use "esp32_ble_tracker:" ?

**Comment by philidinator** [comment]
Hi,
I get the same error :/

`  File "/config/esphome/.esphome/external_components/d599fc18/components/eq3_v2/climate.py", line 8, in <module>
    ESP_PLATFORMS = [ESP_PLATFORM_ESP32]
NameError: name 'ESP_PLATFORM_ESP32' is not defined`

is there a solution? 

thank you

**Comment by ayufan** [comment]
This should now work.

**Comment by jperquin** [comment]
Many thanks. Compiles allright now.

Still getting this error on a few TRV's when running in MQTT:

[0;33m[W][eq3:178]: Climate control of 1a2211f3ca failed. Too many tries.[0m

Not sure if it makes sense to up the retry count?

**Comment by Wojcioo** [comment]
> This should now work.

Now, I've got different error

`INFO Reading configuration /config/esp-eq3-gateway.yaml...`
`INFO Detected timezone 'Europe/Warsaw'`
`Failed config`

`climate.eq3_v2: [source /config/esp-eq3-gateway.yaml:47]`

`  Component climate.eq3_v2 cannot be used together with component esp32_ble_tracker.`
`  platform: eq3_v2`
`  id: office_eq3`
`name: Office EQ3`
`mac_address: 00:1A:22:0E:0A:3A`
`update_interval: 30min`
`valve:`
`name: Office EQ3 Valve State`
`expire_after: 61min`
`esp32_ble_clients: None`
`{}`

**Comment by ayufan** [comment]
As explained. Currently it requires exclusive access to BT and cannot work
with other ble components

**Comment by philidinator** [comment]
It works ! Thank you
